name    'puppet-users'
version '0.0.1'
source 'http://github.com/cwebberOps/puppet-users'
author 'Christopher Webber'
license 'Simplified BSD License'
summary 'Users Module'
description 'Wrapper for Hiera based User Definitions'
project_page 'http://github.com/cwebberOps/puppet-users'
